# wrangler.toml

name = "flare-forms"
workers_dev = true
compatibility_date = "2024-07-24"
main = "src/index.js"

account_id = "${CLOUDFLARE_ACCOUNT_ID}"

[[d1_databases]]
binding = "cloudflareD1"
database_name = "${D1_DATABASE_NAME}"
database_id = "${D1_DATABASE_ID}"

migrations = [
  { dir = "./migrations" }
]

# Email binding
send_email = [
  { type = "send_email", name = "SEB" }
]

# Logs
logpush = true

# Sentry Monitoring
tail_consumers = [{service = "flare-forms-tail"}]

# Vars
[vars]
  FROM_EMAIL = "${FROM_EMAIL}"
  DESTINATION_EMAIL = "${DESTINATION_EMAIL}"
  ESP_URL = "${ESP_URL}"
  CLOUDFLARE_ACCESS_CLIENT_ID = "${CLOUDFLARE_ACCESS_CLIENT_ID}"
  CLOUDFLARE_ACCESS_CLIENT_SECRET = "${CLOUDFLARE_ACCESS_CLIENT_SECRET}"
